### ISSUE TITLE
sequential job execution

### ISSUE THREAD

**Issue by tbrand** [tbrand/neph#60]
Currently all jobs at `depends_on` are executed concurrently.
But sometimes we want to do it sequentially.
(The idea is needed at least [here](https://github.com/tbrand/which_is_the_fastest/pull/180/files))

You may know you can do it like
```
some_job:
  depends_on:
    - sub_job1

sub_job1:
  depends_on:
    - sub_job2
```

But when we remove the `sub_job1` from it, the pipeline will be broken.
So it's not good at the view point of flexibility and stability.

How about adding this function to neph.yaml?
```
some_job:
  depends_on:
    - sub_job1
    - sub_job2
  seq: true
```

When the `seq` config is `true`, the series of jobs on `depends_on` will be executed sequentially.
The default is `false`.

What do you guys think?
